#! python


def build(ctx):

    targets = []
    for country in ["DEU", "FRA", "USA", "ESP", "ITA", "BEL"]:
        targets += [
            ctx.path_to(ctx, "OUT_FIGURES", "covid_time_series_" + country + ".pdf")
        ]

    ctx(
        features="run_py_script",
        source="get_figures.py",
        target=targets,
        deps=[
            ctx.path_to(ctx, "IN_DATA", "country_and_continent_codes.csv"),
            ctx.path_to(ctx, "IN_DATA_OWID", "owid-covid-data.csv"),
        ],
        name="get_data",
    )
